@extends('admin.layouts.app')

@section('title', $testBank->title)
@section('kicker', 'Test Bank Authoring')
@section('toast_notifications', 'true')

@section('header_actions')
<button class="btn-primary" type="button" onclick="openModal('questionModal')">Add Question</button>
<button class="btn-ghost" type="button" onclick="openModal('importModal')">Upload CSV</button>
<button class="btn-ghost" type="button" onclick="openModal('quizModal')">Create Premade Quiz</button>
@endsection

@section('content')
<style>
.tb-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.tb-stat{padding:1rem;border:1px solid var(--border);border-radius:14px;background:var(--surface)}.tb-stat small{display:block;color:var(--text-muted);text-transform:uppercase;letter-spacing:.08em}.tb-stat strong{font-size:1.45rem}.tb-table-wrap{overflow-x:auto}.tb-table{width:100%;border-collapse:collapse}.tb-table th,.tb-table td{padding:.8rem;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}.tb-table th{font-size:.7rem;text-transform:uppercase;color:var(--text-muted)}.tb-question{white-space:pre-line;min-width:280px}.tb-option-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.tb-check-grid{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.tb-check{display:flex;gap:.55rem;align-items:center;padding:.7rem;border:1px solid var(--border);border-radius:10px}.tb-check input{width:auto}.tb-quiz-list{display:grid;gap:.75rem}.tb-quiz{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1rem;border:1px solid var(--border);border-radius:12px}.tb-quiz h3{margin:0 0 .2rem}.tb-quiz p{margin:0;color:var(--text-muted);font-size:.8rem}@media(max-width:700px){.tb-summary,.tb-option-grid,.tb-check-grid{grid-template-columns:1fr}.tb-quiz{align-items:flex-start;flex-direction:column}}
</style>

<div class="toolbar"><div><a class="btn-ghost" href="{{ route('admin.content.test-banks.index', $course) }}" style="display:inline-flex;text-decoration:none;margin-bottom:1rem">← Test Bank Catalogs</a><p class="panel-label">{{ $testBank->code }} · {{ $course->title }}</p><h2 class="panel-title">{{ $testBank->title }}</h2><p class="panel-subtitle">Build the multiple-choice question bank and learner-facing premade quizzes.</p></div></div>
<div class="tb-summary"><div class="tb-stat"><small>Questions</small><strong>{{ $questions->total() }}</strong></div><div class="tb-stat"><small>Premade quizzes</small><strong>{{ $quizzes->count() }}</strong></div><div class="tb-stat"><small>Question format</small><strong>Multiple choice</strong></div></div>

<section class="panel" style="margin-bottom:1rem"><p class="panel-label">Quiz Builder</p><h2 class="panel-title">Premade Quizzes</h2><div class="tb-quiz-list" style="margin-top:1rem">@forelse($quizzes as $quiz)<article class="tb-quiz"><div><h3>{{ $quiz->title }}</h3><p>{{ $quiz->questions_count }} items · Randomized · {{ $quiz->status === 'active' ? 'Available to learners' : 'Inactive' }}</p>@if($quiz->description)<p>{{ $quiz->description }}</p>@endif</div><form method="POST" action="{{ route('admin.content.test-banks.quizzes.destroy', [$course,$testBank,$quiz]) }}">@csrf @method('DELETE')<button class="btn-ghost" style="color:var(--wrong)">Delete</button></form></article>@empty<p class="muted">No premade quizzes created yet.</p>@endforelse</div></section>

<section class="panel"><p class="panel-label">Question Bank</p><h2 class="panel-title">Multiple-Choice Questions</h2><div class="tb-table-wrap"><table class="tb-table"><thead><tr><th>Question</th><th>Subject</th><th>Answer</th><th>Action</th></tr></thead><tbody>@forelse($questions as $question)<tr><td class="tb-question">{{ $question->question }}</td><td>{{ $question->subject?->subject_code }}<br><small>{{ $question->subject?->title }}</small></td><td>{{ chr(65 + $question->correct_answer) }}. {{ $question->options[$question->correct_answer] ?? '' }}</td><td><form method="POST" action="{{ route('admin.content.test-banks.questions.destroy', [$course,$testBank,$question]) }}">@csrf @method('DELETE')<button class="btn-ghost" style="color:var(--wrong)">Delete</button></form></td></tr>@empty<tr><td colspan="4" class="muted">No Test Bank questions yet. Add one manually or upload the CSV template.</td></tr>@endforelse</tbody></table></div><div style="margin-top:1rem">{{ $questions->links() }}</div></section>

<div id="questionModal" class="admin-modal"><form method="POST" action="{{ route('admin.content.test-banks.questions.store',[$course,$testBank]) }}" class="admin-modal-content" style="max-width:820px">@csrf<div class="admin-modal-header"><h3 class="admin-modal-title">Add Multiple-Choice Question</h3><button type="button" class="admin-modal-close" onclick="closeModal('questionModal')">&times;</button></div><div class="admin-modal-body"><div class="form-grid"><div class="field full"><label>Subject</label><select class="form-control" name="subject_id" required><option value="">Select subject</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->subject_code }} — {{ $subject->title }}</option>@endforeach</select></div><div class="field full"><label>Question</label><textarea class="form-control" name="question" rows="4" required></textarea></div><div class="field full"><label>Choices</label><div class="tb-option-grid">@foreach(range('A','H') as $index=>$letter)<input class="form-control" name="options[]" placeholder="{{ $letter }}. {{ $index < 2 ? 'Required choice' : 'Optional choice' }}" {{ $index < 2 ? 'required' : '' }}>@endforeach</div></div><div class="field"><label>Correct answer</label><select class="form-control" name="correct_answer" required>@foreach(range('A','H') as $index=>$letter)<option value="{{ $index }}">{{ $letter }}</option>@endforeach</select></div><div class="field full"><label>Rationale</label><textarea class="form-control" name="rationale" rows="3"></textarea></div></div></div><div class="admin-modal-footer"><button type="button" class="btn-ghost" onclick="closeModal('questionModal')">Cancel</button><button class="btn-primary">Save Question</button></div></form></div>

<div id="importModal" class="admin-modal"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.content.test-banks.questions.import',[$course,$testBank]) }}" class="admin-modal-content" style="max-width:650px">@csrf<div class="admin-modal-header"><h3 class="admin-modal-title">Upload Questions by CSV</h3><button type="button" class="admin-modal-close" onclick="closeModal('importModal')">&times;</button></div><div class="admin-modal-body"><div class="field"><label>CSV file</label><input class="form-control" type="file" name="csv_file" accept=".csv,text/csv" required></div><p class="muted">Use subject codes exactly as saved in {{ $course->title }}. Supports 2–8 choices and up to 5,000 questions per upload.</p><button type="button" class="btn-ghost" onclick="downloadTemplate()">Download CSV Template</button></div><div class="admin-modal-footer"><button type="button" class="btn-ghost" onclick="closeModal('importModal')">Cancel</button><button class="btn-primary">Import Questions</button></div></form></div>

<div id="quizModal" class="admin-modal"><form method="POST" action="{{ route('admin.content.test-banks.quizzes.store',[$course,$testBank]) }}" class="admin-modal-content" style="max-width:720px">@csrf<div class="admin-modal-header"><h3 class="admin-modal-title">Create Premade Quiz</h3><button type="button" class="admin-modal-close" onclick="closeModal('quizModal')">&times;</button></div><div class="admin-modal-body"><div class="form-grid"><div class="field"><label>Quiz title</label><input class="form-control" name="title" required></div><div class="field"><label>Number of items</label><input class="form-control" name="item_count" type="number" min="1" max="500" value="50" required></div><div class="field full"><label>Description</label><textarea class="form-control" name="description" rows="3"></textarea></div><div class="field full"><label>Subjects included</label><div class="tb-check-grid">@foreach($subjects as $subject)<label class="tb-check"><input type="checkbox" name="subject_ids[]" value="{{ $subject->id }}"><span>{{ $subject->subject_code }} — {{ $subject->title }}</span></label>@endforeach</div></div></div><p class="muted">Questions are selected randomly from the chosen subjects. If fewer questions are available than requested, all available questions are used.</p></div><div class="admin-modal-footer"><button type="button" class="btn-ghost" onclick="closeModal('quizModal')">Cancel</button><button class="btn-primary">Save Premade Quiz</button></div></form></div>

<script>
function openModal(id){document.getElementById(id)?.classList.add('open')}function closeModal(id){document.getElementById(id)?.classList.remove('open')}
function downloadTemplate(){const csv='subject_code,question,option_a,option_b,option_c,option_d,option_e,option_f,option_g,option_h,correct_answer,rationale\n{{ $subjects->first()?->subject_code ?? 'SUBJECT-1' }},What is the best answer?,Choice A,Choice B,Choice C,Choice D,,,,,A,Explain why A is correct.';const blob=new Blob([csv],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='artemis-test-bank-questions.csv';link.click();URL.revokeObjectURL(link.href)}
@if(session('success')) document.addEventListener('DOMContentLoaded', () => showAdminToast(@json(session('success')), 'success')); @endif
@if(session('error')) document.addEventListener('DOMContentLoaded', () => showAdminToast(@json(session('error')), 'error', 6500)); @endif
@if($errors->any()) document.addEventListener('DOMContentLoaded', () => showAdminToast(@json(implode(' ', $errors->all())), 'error', 6500)); @endif
</script>
@endsection
