@extends('admin.layouts.app', ['pageTitle' => 'Class Management'])
@section('kicker', 'Batch Delivery')
@php($isAdmin = Auth::user()->is_admin || strtolower((string) Auth::user()->role) === 'admin')

@section('content')
@if($isAdmin)
<section class="panel" style="margin-bottom:1.25rem">
    <div class="panel-label">Batch setup</div><h2 id="class-batch-form-title" class="panel-title">Create Batch</h2>
    <p class="panel-subtitle">Create the class first, then assign one or more reusable master courses.</p>
    <form id="classBatchForm" method="POST" action="{{ route('admin.classes.batches.store') }}">@csrf<input id="class_batch_method" type="hidden" name="_method" value="POST">
        <div class="form-grid">
            <div class="field"><label>Batch name</label><input id="class_batch_name" name="name" required placeholder="OCTOBER 2026 (MWF) FULL"></div>
            <div class="field"><label>Batch code</label><input id="class_batch_code" name="code" required placeholder="OCT26-MWF-FULL"></div>
            <div class="field"><label>Starts</label><input id="class_batch_starts_at" name="starts_at" type="datetime-local"></div>
            <div class="field"><label>Ends</label><input id="class_batch_ends_at" name="ends_at" type="datetime-local"></div>
            <div class="field"><label>Class days</label><input id="class_batch_schedule_day" name="schedule_day" placeholder="Monday, Wednesday, Friday"></div>
            <div class="field"><label>Start time</label><input id="class_batch_start_time" name="start_time" type="time"></div>
            <div class="field"><label>End time</label><input id="class_batch_end_time" name="end_time" type="time"></div>
            <div class="field"><label>Modality</label><select id="class_batch_modality" name="modality"><option value="">Select modality</option><option>Online</option><option>Blended</option><option>Live via Zoom</option></select></div>
            <div class="field"><label>Batch price (PHP)</label><input id="class_batch_price" name="price" type="number" min="0" step=".01" required></div>
            <div class="field"><label>Display price (USD)</label><input id="class_batch_usd_price" name="usd_price" type="number" min="0" step=".01"></div>
            <div class="field"><label>Capacity</label><input id="class_batch_capacity" name="capacity" type="number" min="1"></div>
            <div class="field"><label>Status</label><select id="class_batch_status" name="status"><option value="open">Open</option><option value="draft">Draft</option><option value="closed">Closed</option><option value="completed">Completed</option></select></div>
            <div class="field full"><label for="class_batch_description">Description</label><textarea id="class_batch_description" name="description" rows="3" class="form-control" placeholder="Describe this batch offering, delivery setup, or important learner information."></textarea></div>
            <div class="field full"><label>Included master courses</label><div class="class-course-checklist">@forelse($courses as $course)<label><input type="checkbox" name="course_ids[]" value="{{ $course->id }}"><span>{{ $course->title }}</span></label>@empty<p class="muted">No approved master courses are available.</p>@endforelse</div></div>
        </div>
        <div style="display:flex;justify-content:flex-end;gap:.6rem;margin-top:1rem"><button id="class_batch_cancel" type="button" class="btn-ghost hidden" onclick="resetClassBatchForm()">Cancel Edit</button><button class="btn-primary" type="submit">Save Batch</button></div>
    </form>
</section>
@endif

<section class="panel">
    <div class="panel-label">Classes</div><h2 class="panel-title">Manage Batches</h2><p class="panel-subtitle">Each batch unlocks every master course assigned to it.</p>
    <div class="class-batch-grid">
    @forelse($batches as $batch)
        @php($editor = ['id'=>$batch->id,'name'=>$batch->name,'code'=>$batch->code,'description'=>$batch->description,'starts_at'=>$batch->starts_at?->format('Y-m-d\TH:i'),'ends_at'=>$batch->ends_at?->format('Y-m-d\TH:i'),'schedule_day'=>$batch->schedule_day,'start_time'=>substr((string)$batch->start_time,0,5),'end_time'=>substr((string)$batch->end_time,0,5),'modality'=>$batch->modality,'price'=>$batch->price,'usd_price'=>$batch->usd_price,'capacity'=>$batch->capacity,'status'=>$batch->status,'course_ids'=>$batch->courses->pluck('id')->values()])
        <article class="class-batch-card">
            <div class="class-batch-card-head"><div><small>{{ $batch->code }}</small><h3>{{ $batch->name }}</h3></div><span class="status {{ $batch->status==='open'?'success':'warning' }}">{{ ucfirst($batch->status) }}</span></div>
            <p>{{ $batch->description ?: 'No batch description provided.' }}</p>
            <div class="class-batch-meta"><span><i data-lucide="calendar-days"></i>{{ $batch->starts_at?->format('M d, Y') ?? 'Open schedule' }} – {{ $batch->ends_at?->format('M d, Y') ?? 'No end date' }}</span><span><i data-lucide="clock-3"></i>{{ $batch->schedule_day ?: 'Flexible schedule' }} · {{ $batch->modality ?: 'Online' }}</span><span><i data-lucide="users"></i>{{ $batch->active_enrollments_count }} enrolled</span></div>
            <div class="class-batch-courses"><strong>Included courses</strong>@foreach($batch->courses as $course)<span>{{ $course->title }}</span>@endforeach</div>
            <div class="class-batch-actions"><button class="btn-ghost" type="button" onclick="openClassZoom({{ $batch->id }}, @js($batch->name))">Zoom Calendar ({{ $batch->zoomSessions->count() }})</button>@if($isAdmin)<button class="btn-ghost" type="button" data-batch="{{ json_encode($editor) }}" onclick="editClassBatch(JSON.parse(this.dataset.batch))">Edit</button><form method="POST" action="{{ route('admin.classes.batches.destroy',$batch) }}" onsubmit="return confirmDelete(event,'Delete this batch? Only batches without enrollment history can be deleted.')">@csrf @method('DELETE')<button class="btn-ghost" style="color:var(--wrong)">Delete</button></form>@endif</div>
        </article>
    @empty <p class="muted">No batches have been created.</p> @endforelse
    </div>
</section>

<div id="classZoomModal" class="admin-modal"><div class="admin-modal-content" style="max-width:900px"><div class="admin-modal-header"><div><h3 class="admin-modal-title">Batch Zoom Calendar</h3><p id="class_zoom_batch" class="muted"></p></div><button class="admin-modal-close" onclick="closeClassZoom()">&times;</button></div><div class="admin-modal-body"><form id="classZoomForm" class="panel" style="padding:1rem"><input id="class_zoom_id" type="hidden"><div class="form-grid"><div class="field"><label>Session title</label><input id="class_zoom_title" required></div><div class="field"><label>Zoom link</label><input id="class_zoom_url" type="url" required></div><div class="field"><label>Starts</label><input id="class_zoom_start" type="datetime-local" required></div><div class="field"><label>Ends</label><input id="class_zoom_end" type="datetime-local"></div><div class="field"><label>Status</label><select id="class_zoom_status"><option value="scheduled">Scheduled</option><option value="cancelled">Cancelled</option></select></div><div class="field full"><label>Description</label><textarea id="class_zoom_description" rows="2"></textarea></div></div><div style="display:flex;justify-content:flex-end;gap:.5rem"><button type="button" class="btn-ghost" onclick="resetClassZoomForm()">Clear</button><button class="btn-primary">Save Session</button></div></form><div id="class_zoom_list" class="list-stack" style="margin-top:1rem"></div></div></div></div>

<style>.class-course-checklist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.55rem;padding:.8rem;border:1px solid var(--border);border-radius:12px}.class-course-checklist label{display:flex;align-items:center;justify-content:flex-start;gap:.65rem;min-height:42px;padding:.55rem .7rem;border-radius:8px;background:rgba(47,103,143,.06);cursor:pointer}.class-course-checklist input[type="checkbox"]{appearance:auto;-webkit-appearance:checkbox;flex:0 0 auto;width:16px!important;height:16px!important;min-width:16px;margin:0;padding:0;accent-color:#0bb89d}.class-course-checklist label span{line-height:1.3;text-align:left}.form-control{display:block;width:100%;padding:.75rem .85rem;border:1px solid var(--border);border-radius:10px;background:var(--surface);color:var(--text);font:inherit;line-height:1.5;box-sizing:border-box}.form-control:focus{border-color:#2f678f;outline:0;box-shadow:0 0 0 3px rgba(47,103,143,.14)}.class-batch-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.class-batch-card{padding:1.15rem;border:1px solid var(--border);border-top:4px solid #2f678f;border-radius:15px;background:var(--surface)}.class-batch-card-head{display:flex;justify-content:space-between;gap:1rem}.class-batch-card-head small{color:#f56600;font-weight:800}.class-batch-card h3{margin:.25rem 0}.class-batch-card>p{color:var(--text-muted);font-size:.8rem}.class-batch-meta{display:flex;flex-direction:column;gap:.45rem}.class-batch-meta span{display:flex;align-items:center;gap:.45rem;color:var(--text-muted);font-size:.75rem}.class-batch-meta svg{width:15px;color:#f56600}.class-batch-courses{display:flex;flex-wrap:wrap;gap:.4rem;margin:1rem 0}.class-batch-courses strong{width:100%;font-size:.72rem}.class-batch-courses span{padding:.3rem .55rem;border-radius:999px;color:#245678;background:rgba(47,103,143,.1);font-size:.68rem;font-weight:700}.class-batch-actions{display:flex;gap:.45rem;flex-wrap:wrap}.class-batch-actions form{margin:0}@media(max-width:850px){.class-batch-grid{grid-template-columns:1fr}}@media(max-width:640px){.class-course-checklist{grid-template-columns:1fr}}</style>
<script>
const classCsrf=@json(csrf_token());let activeClassBatch=null;let classZoomSessions=[];
function editClassBatch(item){const form=document.getElementById('classBatchForm');form.action=`/admin/classes/batches/${item.id}`;document.getElementById('class_batch_method').value='PUT';document.getElementById('class-batch-form-title').textContent='Edit Batch';['name','code','description','starts_at','ends_at','schedule_day','start_time','end_time','modality','price','usd_price','capacity','status'].forEach(key=>document.getElementById(`class_batch_${key}`).value=item[key]??'');document.querySelectorAll('input[name="course_ids[]"]').forEach(input=>input.checked=item.course_ids.includes(Number(input.value)));document.getElementById('class_batch_cancel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}
function resetClassBatchForm(){const form=document.getElementById('classBatchForm');form.reset();form.action='{{ route('admin.classes.batches.store') }}';document.getElementById('class_batch_method').value='POST';document.getElementById('class-batch-form-title').textContent='Create Batch';document.getElementById('class_batch_cancel').classList.add('hidden');}
function resetClassZoomForm(){['class_zoom_id','class_zoom_title','class_zoom_url','class_zoom_start','class_zoom_end','class_zoom_description'].forEach(id=>document.getElementById(id).value='');document.getElementById('class_zoom_status').value='scheduled';}
async function openClassZoom(id,name){activeClassBatch=id;document.getElementById('class_zoom_batch').textContent=name;document.getElementById('classZoomModal').classList.add('open');resetClassZoomForm();await loadClassZoom();}function closeClassZoom(){document.getElementById('classZoomModal').classList.remove('open');}
async function loadClassZoom(){const response=await fetch(`/admin/classes/batches/${activeClassBatch}/zoom-sessions`,{headers:{Accept:'application/json'}});const data=await response.json();classZoomSessions=data.sessions||[];document.getElementById('class_zoom_list').innerHTML=classZoomSessions.length?classZoomSessions.map(item=>`<div class="list-item"><strong>${escapeClass(item.title)}</strong><span class="muted">${new Date(item.startsAt).toLocaleString()} · ${escapeClass(item.status)}</span><div style="display:flex;gap:.4rem;margin-top:.6rem"><button class="btn-ghost" onclick="editClassZoom(${item.id})">Edit</button><button class="btn-ghost" style="color:var(--wrong)" onclick="deleteClassZoom(${item.id})">Delete</button></div></div>`).join(''):'<p class="muted">No Zoom sessions scheduled.</p>';}
function editClassZoom(id){const item=classZoomSessions.find(row=>row.id===id);if(!item)return;document.getElementById('class_zoom_id').value=item.id;document.getElementById('class_zoom_title').value=item.title||'';document.getElementById('class_zoom_url').value=item.zoomUrl||'';document.getElementById('class_zoom_start').value=(item.startsAt||'').slice(0,16);document.getElementById('class_zoom_end').value=(item.endsAt||'').slice(0,16);document.getElementById('class_zoom_description').value=item.description||'';document.getElementById('class_zoom_status').value=item.status;}
document.getElementById('classZoomForm').addEventListener('submit',async event=>{event.preventDefault();const id=document.getElementById('class_zoom_id').value;const payload={title:document.getElementById('class_zoom_title').value,zoom_url:document.getElementById('class_zoom_url').value,starts_at:document.getElementById('class_zoom_start').value,ends_at:document.getElementById('class_zoom_end').value||null,description:document.getElementById('class_zoom_description').value||null,status:document.getElementById('class_zoom_status').value};const response=await fetch(`/admin/classes/batches/${activeClassBatch}/zoom-sessions${id?`/${id}`:''}`,{method:id?'PUT':'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':classCsrf},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)return showAdminAlert(Object.values(data.errors||{}).flat().join(' ')||data.message);resetClassZoomForm();await loadClassZoom();});
async function deleteClassZoom(id){const response=await fetch(`/admin/classes/batches/${activeClassBatch}/zoom-sessions/${id}`,{method:'DELETE',headers:{Accept:'application/json','X-CSRF-TOKEN':classCsrf}});if(!response.ok)return showAdminAlert('Unable to delete Zoom session.');await loadClassZoom();}function escapeClass(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML;}
</script>
@endsection
